### ISSUE TITLE
Fix switch_enocean kernel panic 

### ISSUE THREAD

**Issue by BasileCuneo** [smartobjectoriented/soo#32]
There is a kernel panic when booting with both SOO.blind_64 and SOO.switch_enocean_64

**Comment by daniel-rossier** [comment]
Please can you give further details? When is the kernel panic happening? Does it depend on the order of injection? Does it work when MEs are injected as only one?

**Comment by BasileCuneo** [comment]
The kernel panic is happening on switch_enocean injection the blind wasn't linked to it.

**Comment by BasileCuneo** [comment]
The problem has been solved, the last commit also includes fix to make the blind work correctly with the switch enocean ME.
