### ISSUE TITLE
Issue with virt64 & rpi4_64 targets 

### ISSUE THREAD

**Issue by jmi-reds** [smartobjectoriented/soo#5]
The compilation of SOO framework does not fully compile for `virt64` target

**Comment by daniel-rossier** [comment]
There were some misalignment; the compilation is good now, but there is another issue related to the ME bootstrap.
I'm on it (on this branch).

**Comment by daniel-rossier** [comment]
A header file to include config variables (auto.conf) was missing in so3/arch/arm64/head.S. 
Normally, CONFIG_SO3VIRT is set to Y, but since this file was missing, it appeared as unset and compiled a wrong configuration,

**Comment by jmi-reds** [comment]
Re-open -  finial tests and merge-request are still pending

**Comment by jmi-reds** [comment]
Update issue name - there also is some issue with `rpi4_64` target

**Comment by daniel-rossier** [comment]
Could you be more specific? Maybe the term "issue" in the subject is to vague and we should have a more detailed description of the issue to manage the branch.

**Comment by jmi-reds** [comment]
**`rpi4_64` target issue description** 

The `rootfs` compilation failed for `python-sense-hat` package with an error with the hash value.

**root cause**  
This package pointed to the master version of `python-sense-hat`. It has been updated lately which implies a new hash value.

**fix**
The package now points to the v2.5.0 version.

**Comment by act-reds** [comment]
Update issue : 

There is a problem when trying to compile any ME if the library libyaml-0.1 is installed on the system. When using the command `build.sh -k SOO.refso3` for example, a linkage error will appear concerning the yaml functions.

This error comes from the dtc.c file, that is checking a specific environment variable that is set in a Makefile if the libyaml is not found.

**Comment by jmi-reds** [comment]
I've done some experiments regarding the `yaml` issue.

I complied `SOO.refso3_64` on PC running Ubuntu 20.04 et Debian buster (old-stable), both time with `libyaml` installed (package `libyaml-0-2` both time)

No issue reported. I will double check with @act-reds regarding his config but I've the impression that we can complete the pull request.
