### ISSUE TITLE
Use SO3 as submodule

### ISSUE THREAD

**Issue by AnthoJack** [smartobjectoriented/soo#52]
Current integration of SO3 requires manual alignments when SO3 is updated. To mitigate this problem, SO3 should be a submodule of the SOO repository. Files specific to SOO (drivers, target ITS, DTS, configs...) are to be kept in the SOO repository. A script will be used to create a usable SO3 folder from the original SO3 repository and supplementary SOO files

**Comment by daniel-rossier** [comment]
The build is now achieved correctly by means of the ME/work directory. It contains a ``build.sh`` script which will create symlinks to original so3 and to SOO-specific file stored in ME/soo/so3 files.
